project:
  type: website
  output-dir: docs

website:
  title: "Yosephine Manihuruk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

page-footer:
  left: |
    &copy; Yosephine Manihuruk, 2024<br>
    All content licensed under <i class='bi-badge-cc'></i>
    [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
  right: |
    Site built with <a href='https://quarto.org/'>Quarto</a>

